name: QA Demo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.stats()'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Seed test user
      working-directory: backend
      env:
        MONGO_URI: mongodb://localhost:27017/qa-demo-db
        JWT_SECRET: testsecret
      run: node seed.js

    - name: Run API tests
      working-directory: backend
      env:
        MONGO_URI: mongodb://localhost:27017/qa-demo-db
        JWT_SECRET: testsecret
      run: npm run test:api

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Give exec permissions to all node binaries
      working-directory: frontend
      run: chmod +x ./node_modules/.bin/*

    - name: Install Cypress binary
      working-directory: frontend
      run: npx cypress install  

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Run Cypress tests
      working-directory: frontend
      run: npm run test:e2e

        
